js/Sortable.js
Resolving issue from https://github.com/acthp/ucsc-xena-client/issues/23
=> Mitigating lack of mouseover events (issue #37)

css/crosshairs.css, js/Column.js, js/Crosshair.js, js/Spreadsheet.js, js/plotDenseMatrix.js, js/plotMutationVector.js
@acthp This is more for review of where i'm at.  Still more work to do, especially with crosshair lines, and accounting for some edge cases.  Will perform "cleanup" activities once everything looks good: squash commits, whitespaces, comments, etc.
Issue https://github.com/ucscXena/ucsc-xena-client/issues/13
=> Rebased w/ upstream dev

js/plotMutationVector.js
1) Formatted mutation vector data into their respective categories, and made them available for file download.
2) Accounted for all sample scenarios: withMutations, noMutations, blankMutations.
Issue https://github.com/ucscXena/ucsc-xena-client/issues/52
=> Turned on 'download' for Mutation Vector dataset columns

js/containers/addWizardColumns.js, js/parseInput.js, js/views/VariableSelect.js
I created a new file js/parseInput.js for doing the parsing of input at one place as suggested by @acthp. Then, changed in VariableSelect.js and addWizardColumns.js to require the parseInput.js.
=> Fixed #185

js/views/Welcome.js
Converted Welcome.js View to ES6 Classes syntax, Looking forward to converting all other Views to ES6 Classes and stateless syntax (depending on requirements of the module).
=> Converted Welcome.js to ES6 Class syntax and Fixed Issue #183

js/views/CohortSuggest.js, js/views/DiseaseSuggest2.js, js/views/GeneSuggest.js, js/views/PhenotypeSuggest.js, js/views/XAutosuggest.js
Fix for https://github.com/ucscXena/ucsc-xena-client/issues/190: cohort suggestion component ignoring whitespace and matching words.
XAutoSuggest upgraded to use ES6 syntax.
=> For Issue #190

js/AppControls.js, js/Application.js, js/containers/PageContainer.js, js/main.js, js/views/SampleSearch.js, js/views/Stepper.js
@acthp  I'm closing the previous pull request, this one contains Whitespaces fixes and Thanks for the help :)
=> Es6 Conversion and Whitespaces FixUp

js/views/CohortSuggest.js
@acthp  Assuming just like "Help me select a study", the value of search box should remain what the user has typed if no match is found, so instead of "" , making it this.state.value in line 46, ./js/views/CohortSuggest.js
=> Fix issue #200 

js/views/Column.js
For issue #122.
As far as I was able to test - code works fine. But I'm still not quite sure if using `_.values(this.props.data.refGene)[0]` is stable enough and will work in all cases. Comments are highly appreciated.
=> For issue #122: filter out non-coding mutations for MUPIT

js/KmPlot.js, js/km.css
In this PR, I refactor the kmPlot, remove the bootstrap dependencies, and adjust some UI.
In remove bootstrap dependencies part:
1. Replace the bootstrap widget with react-toolbox widget
2. Replace the bootstrap classes with our own classes, defined in "km.css".
In adjust UI part:
1. Align the PDF button
2. Remove the close button(I think there is a close icon in the right top corner, there is no need to have one special close button)
3. Add icon in PDF button and Help button to let them more representative
4. Change the help link with help button, so there is a uniformed UI
5. Change the cursor style (when user hover on the right list, the original cursor style is "text", is as if the list is editable, it is a little bit puzzling, I change it with the default cursor)
6. Adjust the basic …
=> Refactor kmPlot issue #199

js/views/VizSettings.js, js/views/vizSetting.module.css
This is a work in progress PR, in this PR, I will gradually refactor "vizsettings".
The "vizsettings" now looks like the screen shot below:
Three main issues I am working on:
1. Remove bootstrap widgets
2. Remove bootstrap css classes
3. Adjust overlay (The overlay now is above navbar)
=> [WIP] Refactor Vizsettings #199

js/views/ColCard.module.css
the selector was applying globally to the whole menu...
=> fixed vanishing and reapearing column menu issue#213

js/chart.js
This adds the features requested in issue #340 .
I have modified the file chart.js only.
The p value is calculated from the method mentioned in the issue thread.
=> Added p-values to spearman' rank and pearson's rho #340

js/KmPlot.js, js/km.module.css, js/xenaTheme.js
=> Convert "KM Plot" component to MUI. #510.

js/views/Tooltip.js, js/views/Tooltip.module.css
- includes removal of any react toolbox typography
=> Tooltip backdrop is broken when tooltip is frozen. #581.

js/views/GeneSuggest.js, js/views/XAutocompleteSuggest.js
=> fix: Fix dataset selection closing after checking a single checkbox. #656.

js/views/GeneSuggest.js, js/xenaTheme.js
=> Make autocomplete error messages unobscured by the suggestion panel. #658.

js/views/GeneSuggest.js, js/views/XAutocompleteFormControl.js
=> Fix autosuggest helper text to be selectable. #661.

js/initialState.js, js/views/GhostVariableSelect.js, js/views/Sortable.js, js/views/WizardCard.js
=> Columns position is not sortable after adding a new column. #663.

js/chart/chart.js, js/chart/chart.module.css, js/xenaTheme.js
Updates chart UI as per [mock](https://www.figma.com/file/CikQhnq8fvMKPRbg8Ow5PT/Xena-Functional-Gemonics-Explorer?type=design&node-id=428-22196&mode=dev).
Updates include:
- Ensuring the chart container fits within the available screen "real estate"; taking into consideration the new chart actions toolbar (inclusive of chart advanced options) and optionally rendered elements like the welcome banner.
- The new chart actions UI with persistant  "advanced options".
=> Update ChartView chart render and actions UI

js/chart/ChartWizard.js, js/chart/chart.js, js/chart/chart.module.css, js/chart/highcharts_helper.js, js/chart/utils.js, js/models/denseMatrix.js, js/models/segmented.js
=> Show mean, median, and/or percentile on a distribution graph

js/chart/chart.js
=> Fix chart height changes when changing chart type
