ucscXena/ucsc-xena-client

- js/AppControls.js
- js/CohortSelect.js
- js/Select.js
https://github.com/acthp/ucsc-xena-client/issues/18
DatasetSelect.js
1) With new line 29, I originally wanted to use _.find( ), but realized that directly referencing the key was faster.  Moreover, this approach of obtaining the corresponding label for the chosen value, is an attempt at providing consistency in how the chosen value is offered to Select.js via CohortSelect and DatasetSelect.
2) With new line 30 `other = _.assoc(other, "value", dataset.label);`, I am assuming that mutating this.props.other would be problematic, therefore the usage of .assoc( ).  Not sure if React already account for this with their props solution.
> Resolution Attempt for Issue #18

- css/tooltip.css
Had conversation w/ Jing and Mary about removing fixed-width, and allowing tooltip to resize.  For now, this solution is okay.  I am well-aware of edge cases where over-extended strings will cutoff...
This PR corresponds to issue https://github.com/acthp/ucsc-xena-client/issues/20
> Enable Tooltip to dynamically re-size

- js/Column.js
In order for the click event to work in Firefox as intended on an element (e.g. prompt for file download), it has to reside on document.body.  Also tested XENA on Chrome after altering codebase -- works as expected.
Represented in issue https://github.com/acthp/ucsc-xena-client/issues/21
> Fixing Firefox Download Issue (issue #37)

- js/plotMutationVector.js
@acthp I'm not intending for this to be a PR, but something easy for you to see the diff given my question below.  I will all squash commits later.
For data formatting, and ultimately, invoking MuPIT, are you wanting to use `this.props.callback` (e.g. `uiCh.onNext( )` -- line 39 of js/connector-dev.js) under (new) line 272 below?  Or go in a new direction, e.g. write out the logic within the method in scope:  `onMode( )`?
> Add mu pit lik

- js/VizSettings.js
- js/appSelector.js
Issue https://github.com/ucscXena/ucsc-xena-client/issues/38
`dsID` parameter was not available on the state, but instead within the applicable column (which sits on the state).  This is how the dsID was obtained, when providing props to the VizSettings component during initial load of the application.
> Allow normalization setting to work

- js/plotDenseMatrix.js
@acthp I have created a fix to handle even when the whole column is null and tested it (sharing screens) 
**# Complete column is Null**
**# Complete column is not Null, but selecting null area**
**#Complete column is not Null and selecting non-null area**
> Fixed issue#93

- js/views/Column.js
For issue https://github.com/ucscXena/ucsc-xena-client/issues/206.
As for the tooltip, I have implemented it with regards to this issue https://github.com/react-toolbox/react-toolbox/issues/651 and this styling https://github.com/ucscXena/ucsc-xena-client/blob/master/js/views/BookmarkMenu.js#L133.
> 206: disabling mupit link when in chrom view

- js/views/BookmarkMenu.module.css
In this PR, I optimize the Bookmark Nav. When I am developing other parts of the UI, I found that when I click the bookmark nav, the pop nav will overlay the "BookMark" button, I feel a little wired of this UX. So I move it a little bit lower. I hope this change will give users better UX.
The original look:
The new look:
If the pop nav need further optimize, I can continue working on it.
Thanks.
> Optimize Bookmark Nav

- js/StateError.js
- js/StateError.module.css
The first edition of StateError will overlay the navbar and footer, sorry for not notice this, this PR, optimize the StateError, do the following changes to StateError:
1. StateError will not overlay the navbar and footer
2. The body of page become scrollable
3. Adjust the length of StateError to have a more fancy UI
New StateError screen shot:
Old StateError screen shot:
The change to StateError is the same as the last change to kmPlot.js, I will pay attention to this overlay problem when I refactor other part of views in the future. @acthp 
Thanks.
> Fix stateError overlay #199

- js/views/VariableSelect.js
the onAddFeature function, for a random search having no match in the 'features' the value of i is -1.
When this.setState was called inside the if statement,an error features[-1] is undefined occured which stopped the execution of code this.on.field("").
> Fixed Phenotype search problem on pressing return

- js/KmPlot.js
- js/StateError.js
- js/views/VizSettings.js
In this PR, I enhance the UX of dialog. In the previous version, when opening a dialog, for example, KM plot, if the page has already been scrolled down a lot, client window may show only part of the dialog. I fix it to let the page scroll to top when dialog did mount. Now user can always see narbar and full dialog in the window after dialog rendered.
I did this kind of change to all dialogs, I hope this change can enhance the UX, looking forward for your review and suggestions. @acthp 
Screen shot of the situation which may happens before:
Screen shot of the dialog now, always show narbar at the top of client window:
> Enhance dialog to scroll page to top

- js/KmPlot.js
- js/km.module.css
- js/views/Column.js
In this PR, I replace all glyphicon with material icon, and adjust the css to fix UI problem caused by using material icon.
The reason I do this change is that the glyphicon is bootstrap icon, when we remove the bootstrap css from the project, the glyphicon we use before will not show. This PR is preparing for remove bootstrap css from main.js.
Use kmPlot for example, when remove bootstrap css, the icon will not show, the screen shot is as shown below:
The screen shot of the kmPlot now (after remove bootstrap):
Looking forward for your review and suggestions. @acthp
> Replace glyphicon with material icon

- js/underscore_ext.js
- js/views/VizSettings.js
As vizsettings was originally plain javascript, in this PR, I rewrite part of vizsettings in a more "normal react" way. The changes I did are listed below:
1. Rename React class to uppercase(the original lower case can not be used as &lt;XXX /&gt;)
2. Write new React classes to replace original static dom functions
3. Replace document.createElement() with native react class tag
4. Move util function valToStr to underscore_ext.js
5. Organize all utils functions in a inner object settingUtils (In this way, it will be easier for us to organize these kind of logics in future, not scattered in different parts)
6. Delete useless img import
Looking forward for your review and suggestions. @acthp 
Thanks.
> Rewrite vizsettings in normal react code

- js/Datapages.module.css
In this PR, I fix the table layout in "DataPage", for example, when we choose the "Treehouse public expression dataset (July 2017)" and then choose "Expected_count" Hub, we will see the table overflow the right side of parent node, as the screen shot shows below:
The table will not overflow the parent node after this fix, the UI now is as shown below:
Looking forward for your review and suggestions. @acthp
> Fix table overflow parent node in datapage

- js/nav.js
ATTN: @jingchunzhu  / @acthp 
Related to https://github.com/ucscXena/XenaGoWidget/issues/205
Conversely, this is an external link out.  We could also do this internally as its an npm widget, but might need some integration help to make the code more closely align:
https://www.npmjs.com/package/ucsc-xena-geneset
> added a nav link for geneSets - needs feedback

- js/nav.js
- The Nav component is rendered after the core Application component. In doing so, the theme provider specific to the Nav component is injected last (after the Application component theme provider).
- To ensure nav-specific theme styles are not overriding core theme styles, a Mui `StylesProvider` component was added to the Nav component with `injectFirst` and `generateClassName` props.
- Unfortunately, by injecting the nav styles first, styles like `.material-icons`, were overriding the nav styles.
- Because the nav styles provider uses a class name generator to namespace the Mui styles, the removal of the `injectFirst` is a suitable solution, because namespacing is sufficient to ensure nav-specific theme styles are not overriding core theme styles.
> Nav styles provider injection order reverted to last. #520.

- js/views/Stepper.js
- js/xenaColor.js
- js/xenaTheme.js
- Typically the Mui Stepper places an element - a connector line - between each step (see [Mui Stepper](https://v4.mui.com/components/steppers/#horizontal-stepper)).
- The Xena stepper places a connector line after each step (including the last).
- The original solution was to set the `Stepper` prop `connector` to null and insert the component `StepConnector` after each `StepLabel`, however, this generates an error.
- This PR resolves this error by hand-rolling the connector.
> Convert 'Stepper' component to MUI. Bug fix for unconventional use of StepConnector component. #493.

- js/views/ColCard.js
> When zoomed into a single column, the close icon too big. #571.

- js/chart/ChartWizard.js
- js/chart/chart.js
- js/xenaTheme.js
- Remove `cardHeader` and relocated close `x` icon to `cardContent` with position absolute.
- Modified ChartWizard to ensure longer select options wrap.
> Added vertical space above the title in charts. #600.

- js/views/ColCard.js
- js/views/ColCard.module.css
- js/views/Column.js
- Disables all column interaction while in wizard or edit mode, as well as while card status is "loading".
> Disable all column interaction while in wizard or edit mode. #654.
